#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: apdp
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"

testing:
  app: apdp-testing
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test"
